name: "Auto-generate CHANGELOG"
description: "Generate CHANGELOG according to conventional commits automatically when released"
author: "BobAnkh"
branding:
  icon: 'award'
  color: 'orange'
inputs:
  REPO_NAME:
    description: "The name of the repo: user/repo_name"
    required: true
  ACCESS_TOKEN:
    description: "Github Access Token you want to use. Just pass GITHUB_TOKEN"
    required: true
  PATH:
    description: "Path to the file you want to add contributors' list. You can use <branch>:<file> format to specify the branch"
    required: false
    default: '/CHANGELOG.md'
  COMMIT_MESSAGE:
    description: "Commit message"
    required: false
    default: 'docs(CHANGELOG): update release notes'
  TYPE:
    description: "The type of commits you want to add to CHANGELOG"
    required: false
    default: 'feat:Feature,fix:Fix'
runs:
  using: "docker"
  image: "Dockerfile"
