name: Generate changelog
on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - develop
      - master
pull_request:
      # Only following types are handled by the action, but one can default to all as well
      types: [ opened, reopened, synchronize ]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog

