name: Generate changelog
on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - develop
      - master
  pull_request:
      # Only following types are handled by the action, but one can default to all as well
      types: [ opened, reopened, synchronize ]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Semantic Release
        uses: ./
        with:
          branch: master
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
