name: Add a new issue to the specified project column
on: 
  issues:
    types: [opened]
jobs:
  add-new-issues-to-project-column:
    runs-on: ubuntu-latest
    steps:
    - name: add-new-issues-to-repository-based-project-column
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/BobAnkh/LinuxBeginner/projects/3
        GITHUB_PROJECT_COLUMN_NAME: To do
