on: 
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
name: pytest
jobs:
  Pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: GitHub Action for pytest
      uses: cclauss/GitHub-Action-for-pytest@master
      with:
        args: pytest -vv
